2020-08-05 14:44:13,531 -- ERROR -- в файле config_client_log.py -- в строке 24 в файл и консоль
